language: node_js
node_js:
  - 12

services:
  - postgresql

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registration_numbers_tests

before_script:
  - psql -c 'create database  registration_numbers_tests;' -U postgres
  - psql -U postgres -d registration_numbers_tests -a -f tables.sql
